export const supportMemories = [
  {
    img: '',
    name: 'None',
    effect: '',
    value: 1,
  },
  {
    img: 'gokugetmarried.png',
    name: 'Goku Gets Married!',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_10004.png',
    name: "Martial Artist's Mettle",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_10005.png',
    name: 'Meet the Flying Nimbus',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_10005.png',
    name: 'Meet the Flying Nimbus',
    effect: 'DEF +30% (All buff)',
    value: 1.3,
  },
  {
    img: 'support_memory_thumb_10006.png',
    name: 'First Friend Ever',
    effect: 'DEF +18%',
    value: 1.18,
  },
  {
    img: 'support_memory_thumb_10006.png',
    name: 'First Friend Ever',
    effect: 'DEF +26% (All buff)',
    value: 1.26,
  },
  {
    img: 'support_memory_thumb_10007.png',
    name: 'Reunion Guided by Fate',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_20002.png',
    name: 'Secret Feelings',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_20004.png',
    name: 'Transcend the Super Saiyan!',
    effect: 'DEF +15% (Super Saiyans buff)',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_20004.png',
    name: 'Transcend the Super Saiyan!',
    effect: 'DEF +25% (Super Saiyan 2 buff)',
    value: 1.25,
  },
  {
    img: 'support_memory_thumb_20004.png',
    name: 'Transcend the Super Saiyan!',
    effect: 'DEF +40% (Full buff)',
    value: 1.4,
  },
  {
    img: 'support_memory_thumb_20005.png',
    name: 'Power Level 530000',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_20006.png',
    name: 'Warrior Awakened through Fury',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_20007.png',
    name: "Gohan's Tears",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_20008.png',
    name: 'Curious Destiny',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_20009.png',
    name: "Captain Ginyu's Super Fighting Pose",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_20011.png',
    name: 'Bonds Forged in the Past',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_20012.png',
    name: "Vegeta's Pride",
    effect: 'DEF +25%',
    value: 1.25,
  },
  {
    img: 'support_memory_thumb_20013.png',
    name: "Krillin's Astonishing Power-Up",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_20014.png',
    name: 'Declaration of the Cell Games',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_20015.png',
    name: 'Gift from Piccolo',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_20016.png',
    name: 'Wavering Thoughts',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_20018.png',
    name: "Goku's Compassion",
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_20019.png',
    name: 'Android #16 Activated!',
    effect: 'DEF +16%',
    value: 1.16,
  },
  {
    img: 'support_memory_thumb_20020.png',
    name: 'Get Even Stronger!',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_20021.png',
    name: 'Bardock and Kakarot',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_20022.png',
    name: 'Please Go! #18',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_30004.png',
    name: 'In Unison! Piccolo and Dende',
    effect: 'DEF +25%',
    value: 1.25,
  },
  {
    img: 'support_memory_thumb_30006.png',
    name: 'Farewell, Goku!',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_30008.png',
    name: 'Shenron as an Enemy?!',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_30010.png',
    name: "Pan's First Kiss",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_30011.png',
    name: 'A Photo Full of Memories',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_30012.png',
    name: 'A Hundred Years Later...',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_30013.png',
    name: 'Confident Gogeta',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_30014.png',
    name: 'To the Infinite Galaxy and Beyond',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40002.png',
    name: "Master and Disciple's Goal",
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40003.png',
    name: "Zen-Ohs' Welcome Words",
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40004.png',
    name: 'Bond of Sister and Brother',
    effect: 'DEF +18%',
    value: 1.18,
  },
  {
    img: 'support_memory_thumb_40005.png',
    name: "Trunks and Mai's Reunion",
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_40005.png',
    name: "Trunks and Mai's Reunion",
    effect: 'DEF +20% (Full buff)',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40006.png',
    name: 'Bulla Is Born!',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40007.png',
    name: 'Two Zamasus',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40008.png',
    name: 'Lamentation of the Absolute God',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40009.png',
    name: "Trunks and Mai's Departure",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_40010.png',
    name: 'The Miracle of Super Hercule?!',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_40010.png',
    name: 'The Miracle of Super Hercule?!',
    effect: 'DEF +20% (Full buff)',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40011.png',
    name: 'Endless Battles of Saiyans',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_40013.png',
    name: 'Two Zen-Ohs',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_40014.png',
    name: 'To the World of Void',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_50001.png',
    name: 'Fly, Icarus!',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_50002.png',
    name: 'Krillin Sings His Heart Out',
    effect: 'DEF +8%',
    value: 1.08,
  },
  {
    img: 'support_memory_thumb_50003.png',
    name: 'Kakarot',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_50004.png',
    name: 'Curiosity About the Realm of Gods',
    effect: 'DEF +25%',
    value: 1.25,
  },
  {
    img: 'support_memory_thumb_50005.png',
    name: 'Strike from the Otherworld',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_50005.png',
    name: 'Strike from the Otherworld',
    effect: 'DEF +25% (Full buff)',
    value: 1.25,
  },
  {
    img: 'support_memory_thumb_50006.png',
    name: "Cooler's Cold Remark",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50007.png',
    name: 'Cruel Provocation',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_50008.png',
    name: 'Rescue Gohan!',
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_50009.png',
    name: "Gohan's Heart",
    effect: 'DEF +20%',
    value: 1.2,
  },
  {
    img: 'support_memory_thumb_50010.png',
    name: 'Gift from the Hero',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50011.png',
    name: "God of Destruction's Pride",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50012.png',
    name: 'Super Hero Fading Away',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50014.png',
    name: "Goku and Chi-Chi's Interview",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50015.png',
    name: "Broly's Inner Power",
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50017.png',
    name: 'Powerful and Gentle Father',
    effect: 'DEF +15%',
    value: 1.15,
  },
  {
    img: 'support_memory_thumb_50020.png',
    name: 'Thank You',
    effect: 'DEF +10%',
    value: 1.1,
  },
  {
    img: 'support_memory_thumb_50021.png',
    name: 'Pan Flying in the Sky',
    effect: 'DEF +5%',
    value: 1.05,
  },
];

/** Valeur du premier support memory (sélection par défaut du formulaire). */
export const DEFAULT_SUPPORT_MEMORY_VALUE = supportMemories[0].value;
